[env:esp32dev]
platform = espressif32 @ ^6.7.0   ; Arduino-ESP32 core 2.x (ledcSetup/ledcAttachPin API)
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    adafruit/Adafruit GFX Library
    adafruit/Adafruit ILI9341
    paulstoffregen/OneWire
    milesburton/DallasTemperature
